// Arithmetic Operators: Operands (values, variables, etc.) Operators (+ - * /)

let students = 30;
students = students + 1;
console.log(students);
students = students - 1;
console.log(students);
students = students * 2;
console.log(students);
students = students / 2;
console.log(students);
students = students ** 2;
console.log(students);
let extraStudents = students % 3;
console.log(extraStudents);
students += 1;
console.log(students);
students -= 1;
console.log(students);
students *= 2;
console.log(students);
students /= 2;
console.log(students);
students **= 2;
console.log(students);
students %= 2;
console.log(students);
students++;
console.log(students);
students--;
console.log(students);